version = 1

test_patterns = ["pymc3/tests/**"]

exclude_patterns = [
    "binder/**",
    "conda-envs/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
